### PR TITLE
chore(type): add native return types

### PR DESCRIPTION
**Pull request by mremi**

### CODE REVIEW

**Comment by kbond** [comment]
Thanks for the PR @mremi. I'm concerned about the potential BC break as none of these methods are final.

**Comment by mremi** [comment]
> Thanks for the PR @mremi. I'm concerned about the potential BC break as none of these methods are final.

Yep, I did it because symfony/error-handler logs all those definitions as deprecated. The alternative could be adding some phpdoc of course, but IMO this BC is a good point to make the code stronger. WDTY?

**Comment by kbond** [comment]
Out of an abundance of caution, I'd like to go with phpdoc for the non-final/non-private/non-test methods. At least until a time laminas-diagnostics adds true return types or until the next major version of this bundle (this is on my list).

**Comment by mremi** [comment]
Ok, done, let me know

**Comment by kbond** [comment]
Thank you @mremi.

**Comment by mremi** [comment]
You're welcome, when do you think bump a new release?

**Comment by kbond** [comment]
Just released v2.17.1.

**Pull request merged**
