### PR TITLE
Added option to specify custom view template

### PR DESCRIPTION
**Pull request by pierredup**
This allows you to override the default template with a custom one

### CODE REVIEW

**Comment by kbond** [comment]
What I don't like about the controller is that it doesn't use twig to render the template. This prevents me from the twig goodness such as extending my base template. I always end up using my own controller... If this is useful for you, I see no issues though.

@lsmith77 I seem to recall you explaining the reasoning for doing the controller/template this way but I can't remember what it is.

**Comment by lsmith77** [comment]
the reason is that we wanted to keep the requirements as low as possible. its entirely possible to use this Bundle for a REST API that doesn't even include any templating at all.

**Comment by kbond** [comment]
Ok, fair enough.

@pierredup for my custom heath check controller, I have the following:

```php
public function healthAction()
{
    $reporter = new ArrayReporter();
    $runner = $this->get('liip_monitor.runner');
    $runner->addReporter($reporter);
    $runner->run();

    return $this->render('@AppBundle/health.html.twig', array('results' => $reporter->getResults()));
}
```

**Comment by lsmith77** [comment]
one thing though .. we could of course optionally support twig

**Pull request merged**
