### PR TITLE
Update SymfonyVersion check to use packagist and check for end of life

### PR DESCRIPTION
**Pull request by kbond**
I was annoyed that an up-to-date 2.3 or 2.8 branch was causing a warning indicating to upgrade to 3.0.0.

This change does 2 things:

1. Checks with http://symfony.com/roadmap?version=3.0#checker to see if your current version is still maintained. It returns a `Failure` if not. This check is done before the version check below.
2. The latest version check just looks at new bug-fix releases for your current version. ie 2.3.33 would cause a warning indicating to upgrade to 2.3.35. This might be considered a BC break but I think it is negligible. I also use the packagist api instead of github now.

Thoughts?

### CODE REVIEW

**Comment by kbond** [comment]
The style failure is unrelated.

**Comment by lsmith77** [comment]
I like it .. due to the minor BC break .. maybe it should go into a new minor version?

**Comment by kbond** [comment]
Sure, it adds a new feature anyway

**Comment by lsmith77** [comment]
created a PR for the style issue https://github.com/liip/LiipMonitorBundle/pull/121

**Comment by lsmith77** [comment]
style issue should go away after a rebase

**Comment by kbond** [comment]
Good to go on this one then?

**Comment by lsmith77** [comment]
also need to bump the minor version in composer

**Pull request merged**
