### PR TITLE
#98 write alias for checks in monitor:list

### PR DESCRIPTION
**Pull request by dav-m85**
Solves https://github.com/liip/LiipMonitorBundle/issues/98

### CODE REVIEW

**Comment by lsmith77** [comment]
@kbond you suggested using tables for this. what do you think of the proposed approch or do you still prefer using a table, ie. http://symfony.com/doc/current/components/console/helpers/tablehelper.html

**Comment by kbond** [comment]
Not a big deal really, just might be more ascetically pleasing to have it in a table.

**Comment by dav-m85** [comment]
I kept it that way because of sf2.1 compatibility on my 1.1branch we were talking about earlier.

**Comment by lsmith77** [comment]
ok good point .. lets keep it simple then.

**Pull request merged**
