### PR TITLE
Added memcached

### PR DESCRIPTION
**Pull request by dev-sl**

### CODE REVIEW

**Comment by lsmith77** [comment]
looks good to me. 

the version bump should be safe I guess:
https://packagist.org/packages/zendframework/zenddiagnostics

**Comment by IgorTimoshenko** [comment]
@lsmith77, make a new tag, please

**Comment by lsmith77** [comment]
sorry its taking so long .. we still need to sort out a few things .. I hope to have time for it over the weekend.

specifically we need 
https://github.com/liip/LiipMonitorBundle/pull/182 and https://github.com/liip/LiipMonitorBundle/pull/184 to be ready

we then want to move to a new minor version which will include this PR

**Comment by IgorTimoshenko** [comment]
@lsmith77, thanks!

**Comment by dev-sl** [comment]
@lsmith77, thanks!

**Pull request merged**
