### PR TITLE
Make routing compatible with all Symfony versions

### PR DESCRIPTION
**Pull request by kbond**
Fix for #179 

@calinpristavu, @cjprinse can you confirm this PR solves the problem?

### CODE REVIEW

**Comment by lsmith77** [comment]
hmm Mathew did a 1.2.0 release of ZF diagnostic more or less on his own in a short time frame but from a quick skim the “Unkown” result class seems unaffacted:
https://github.com/zendframework/zend-diagnostics/compare/v1.1.0...master

so not sure what is causing these failures. the test suite doesn’t seem to use the routing file from the Bundle .. odd

**Comment by kbond** [comment]
It seems the `--prefer-lowest` test isn't working correctly either.

**Comment by lsmith77** [comment]
hmm Mathew did a 1.2.0 release of ZF diagnostic more or less on his own in a short time frame which removed the Unkown class
https://github.com/zendframework/zend-diagnostics/compare/v1.1.0...master#diff-64373d249edac47a45915c550f06902f

I guess if we need this class in our tests .. we should just duplicate it.

**Comment by lsmith77** [comment]
but I guess those issues are actually unrelated to this PR

**Comment by lsmith77** [comment]
thx @kbond !

**Comment by calinpristavu** [comment]
Thanks @kbond 
@lsmith77 the [tag](https://github.com/liip/LiipMonitorBundle/tree/2.6.6/Resources/config) is still broken.
If for whatever reason someone has a fixed version in composer.json, the routing won't work with sf<4.1

**Comment by lsmith77** [comment]
yes .. but there is now a 2.6.7 tag that should work ..

I will delete the 2.6.6 tag I guess. wdyt @kbond ?

**Comment by kbond** [comment]
@lsmith77 I don't think deleting the tag is a good idea. I think it could break deploys that have 2.6.6 in their composer.lock file.

**Pull request merged**
