### PR TITLE
Add support for PHP 8

### PR DESCRIPTION
**Pull request by lepiaf**

### CODE REVIEW

**Comment by lepiaf** [comment]
PR is blocked by a dependency https://github.com/laminas/laminas-diagnostics

```
composer update -n --prefer-dist --prefer-stable

Loading composer repositories with package information

Updating dependencies

Your requirements could not be resolved to an installable set of packages.

  Problem 1

    - laminas/laminas-diagnostics[1.5.0, ..., 1.6.x-dev] require php ^5.6 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.

    - Root composer.json requires laminas/laminas-diagnostics ^1.5 -> satisfiable by laminas/laminas-diagnostics[1.5.0, 1.6.0, 1.6.x-dev].
```

We have to wait merge of PR https://github.com/laminas/laminas-diagnostics/pull/15 and a new version.

**Comment by kbond** [comment]
Great, thanks for working on this @lepiaf!

**Comment by kbond** [comment]
Hey @lepiaf, we just switched to GH actions so you'll have to rebase/adjust this PR (once laminas/laminas-diagnostics#15 is complete).

**Comment by kbond** [comment]
@lepiaf can you rebase?

**Comment by kbond** [comment]
Thanks @lepiaf!

**Pull request merged**
