### PR TITLE
Fix broken helper

### PR DESCRIPTION
**Pull request by cordoval**
addresses https://github.com/liip/LiipMonitorBundle/issues/149

### CODE REVIEW

**Comment by cordoval** [comment]
@lsmith77 have you seen this? opinion?

**Comment by lsmith77** [comment]
it looks like one of the functional tests then also needs to be adjusted.
aside from this .. wondering now if maybe we should instead of all those if conditions simply have two different helper xml files with the service definitions and simply decide which version to load rather than defining/adjusting service definitions via php.

wdyt?

**Comment by cordoval** [comment]
loading of independent xmls will force us to create another setting key though (becoming confusing maybe, what the name would be)
there are use cases:
```
 enable controllers - force need of helper   (load xml)
 disable controllers -  want helper                (load xml)
 disable controllers -  does not want helper   (don't load xml)
```

the last two require a 'want_helper' key should i add this or do we do it like i did in this PR?

**Comment by lsmith77** [comment]
no, my idea would be to choose automatically the right file based on if asset services are available or not.

**Comment by cordoval** [comment]
can it be done though prior to have the container compiled on the first round?

**Comment by cordoval** [comment]
maybe take over this one @lsmith77 you know better what needs to happen and how, i tried but was not able to finish it

**Comment by lsmith77** [comment]
ok thx .. will have a look

**Comment by lsmith77** [comment]
see https://github.com/liip/LiipMonitorBundle/pull/165

**Pull request closed without merging**
