### PR TITLE
Replace continue by break in a switch cases

### PR DESCRIPTION
**Pull request by bmehdi**
To avoid Warning in php 7.3 : `Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?`

### CODE REVIEW

**Comment by lsmith77** [comment]
do you have time to investigate the failure? that being said, I suspect that its caused by a change in ZendDiagnostics.

**Comment by bmehdi** [comment]
> do you have time to investigate the failure? that being said, I suspect that its caused by a change in ZendDiagnostics.

In https://github.com/liip/LiipMonitorBundle/pull/196.

**Comment by lsmith77** [comment]
ok merged .. please rebase :)

**Comment by lsmith77** [comment]
merci https://github.com/liip/LiipMonitorBundle/releases/tag/2.7.3 !

**Comment by bmehdi** [comment]
de rien ;)

**Pull request merged**
