### PR TITLE
Added exception when guzzle is not included

### PR DESCRIPTION
**Pull request by pierredup**

### CODE REVIEW

**Comment by kbond** [comment]
The guzzle check allows for guzzle 4/5 as well. See: https://github.com/zendframework/ZendDiagnostics/blob/master/src/ZendDiagnostics/Check/GuzzleHttpService.php#L144

**Comment by kbond** [comment]
Also, the latest ZendDiagnostics will throw an exception if guzzle is not present. I see there is not a release that includes it. @lsmith77 can you tag a release of ZendDiagnostics?

**Comment by pierredup** [comment]
Thanks @kbond, if a new version of ZendDiagnostics is tagged that includes the exception, then I will close this PR.

**Comment by lsmith77** [comment]
https://github.com/zendframework/ZendDiagnostics/releases/tag/v1.0.4

**Pull request closed without merging**
