### PR TITLE
#99 --reporters option for monitor:list command

### PR DESCRIPTION
**Pull request by dav-m85**
Solving https://github.com/liip/LiipMonitorBundle/issues/99

### CODE REVIEW

**Comment by lsmith77** [comment]
thanks .. sorry but I got this idea just now .. maybe its possible to do this as a separate command with ``monitor:list:reporters`` .. not sure if this works if we also have ``monitor:list`` .. could you try that?

**Comment by dav-m85** [comment]
@lsmith77 I'm not a big fan of this idea. We got a lot of bundles installed on our projects and it sums to a hundred of commands available. Adding commands with limited changes would add to the mess IMHO. That's the reason I proposed an argument instead of an option/separate command at the beginning.
```bash
app/console monitor:list reporters
app/console monitor:list checks

# ... feels more natural to me than
app/console monitor:list
app/console monitor:list:reporters
```

**Comment by lsmith77** [comment]
ok .. I am fine with the argument, which defaults to ``check`` for BC

**Comment by kbond** [comment]
Currently this PR has `--reporters` as an option, are you changing that? I'd prefer to keep it as is.

**Comment by lsmith77** [comment]
Ah, I preferred it as an argument. But its not a big deal for me, so @kbond if you prefer it as is, feel free to merge.

**Comment by kbond** [comment]
I just feel an argument is supposed to be _free form_

**Comment by dav-m85** [comment]
@kbond well you could argue with that too, ```git flabadabada``` doesn't work, right ;) But anyway, okay for the option, and thanks for the merge :tada:

**Pull request merged**
