### PR TITLE
Improved Routing fix

### PR DESCRIPTION
**Pull request by kbond**
A better fix for #179 

I tested on 4.0 and 4.1.

### CODE REVIEW

**Comment by lsmith77** [comment]
awesome .. according to @Tobion he expects this fix should work at least for 3.3.

I would then suggest we also add a “legacy” routing file for users of 2.7/2.8 since they will only go EOL in 2019 but I would suggest we wait for this until we do the minor release in which we also drop PHP 5.6 .. wdyt?

**Comment by Tobion** [comment]
Why not just drop support for SF < 3.3? You can keep a branch for the old code in case there is an important bug fix or security fix.

**Comment by lsmith77** [comment]
@kbond so I retriggered the tests on travis and they are now green.

given that we have 2.6.7 which included the PHP routing file .. I am not worried about removing it again. can we keep the file but load the xml file from there? wdyt?

```
// config/routes.php
use Symfony\Component\Routing\RouteCollection;

$routes = new RouteCollection();
$routes->addCollection(
    $loader->import("@LiipMonitorBundle/Resources/config/routing.xml")
);

return $routes;
```

**Comment by lsmith77** [comment]
so creating https://github.com/liip/LiipMonitorBundle/pull/186 as a follow up

**Pull request merged**
