### PR TITLE
docs: add info on limit for OhDear

### PR DESCRIPTION
**Pull request by Chris53897**
https://github.com/liip/LiipMonitorBundle/pull/289#issuecomment-1868518201

### CODE REVIEW

**Comment by kbond** [comment]
Should we hard code the results limit to 50 so at least the first 50 run?

**Comment by Chris53897** [comment]
Good idea. But OhDear can change this limit anytime.

**Comment by kbond** [comment]
Yeah that's true but right now, none run, correct? I guess we'll just need to update as required...

**Comment by kbond** [comment]
Did you hit this limit?

**Comment by kbond** [comment]
The alternative would be to throw an exception I guess. Force users to add to a suite that's size is less than 50. I'd be fine with that also.

**Comment by Chris53897** [comment]
For now i would suggest to leave it as it is. As there are more important other tasks for me personally.
I do not hit this limit.

**Comment by kbond** [comment]
Fine by me

**Pull request merged**
