### PR TITLE
Make the HTTP failure status code configurable.

### PR DESCRIPTION
**Pull request by tobz**
This PR is an implementation of #213.  As discussed, the value is set to have the default be the existing 502 value.

Questions of mine: looks like there's no existing test for the controller... should there be?

### CODE REVIEW

**Comment by kbond** [comment]
Looks like the parameter is not being set (this is why the test is failing). Should set around here: https://github.com/liip/LiipMonitorBundle/blob/7a3bc243a4a8a4af5e17a7f7441dfe1f53bc30cf/DependencyInjection/LiipMonitorExtension.php#L65

As for the tests, would be nice but won't hold you to adding them before merging.

**Comment by tobz** [comment]
Ah great... I ran phpumit locally but it seemed to pass. Glad the CI caught my mistake. Will fix!

**Comment by kbond** [comment]
Looks good, @lsmith77, any objections?

**Comment by lsmith77** [comment]
fine for me

**Comment by kbond** [comment]
tagged 2.9.0

**Comment by tobz** [comment]
Thanks all!

**Pull request merged**
