### PR TITLE
chore: add tests for php 8.2 and 8.3, update tests to symfony 6.4, drop support symfony 4

### PR DESCRIPTION
**Pull request by Chris53897**
bump github actions

### CODE REVIEW

**Comment by kbond** [comment]
I'm ok with requiring 5.4+

**Comment by Chris53897** [comment]
Update to use `actions/checkout@v4`

**Comment by Chris53897** [comment]
I am not sure if i read your comment correct, to drop support of symfony 4.4.
I changed the ci matrix. Please have a look if this suits the needs of this repo.

**Comment by kbond** [comment]
Perfect, thanks @Chris53897!

**Pull request merged**
