### PR TITLE
[RFC] 3.x

### PR DESCRIPTION
**Pull request by kbond**
Looking for feedback on the next iteration of this bundle.

See [README](https://github.com/kbond/LiipMonitorBundle/blob/next-3.x/README.md) for docs, specifically the [upgrade notes](https://github.com/kbond/LiipMonitorBundle/blob/next-3.x/README.md#upgrading-from-2x-to-3x).

TODO
- [ ] remove need for `Check::label()` (use class short name by default)
- [ ] add remaining missing checks from 2.x
- [ ] re-add email notification
- [ ] Event docs
- [ ] Logging event subscriber
- [ ] _Nagios_ support? I have no idea what this is - does anyone need it? If so, what's required?

### CODE REVIEW

**Comment by wouterj** [comment]
Removing the JSON endpoint is a bit of a bummer for us, as we use this endpoint in our uptime monitor (monitoring the server being up, and having access to all important external services in 1 call). But it's quite easy to introduce this in our applications instead, and I can understand why you don't want to penetrate the application layer in a bundle :)

**Comment by kbond** [comment]
I'm cool keeping the json endpoint but it would be a specific implementation. If there are specific _standard_ formats different services require, I'm fine adding these. The main thing I'd like to remove is the html web interface.

I've made the `ResultSet` `JsonSerializable` with a basic implementation. Apps can add their own normalizer(s).

There are just so many ways you'd want the endpoint to behave. Use status codes? Do warnings constitute failures?

Should I perhaps keep the existing json endpoints as-is so there's no BC break there?

**Comment by wouterj** [comment]
> There are just so many ways you'd want the endpoint to behave. Use status codes? Do warnings constitute failures?
>
> Should I perhaps keep the existing json endpoints as-is so there's no BC break there?

About the behavior: I have experience with 3 uptime monitors, and all of them required me to specify when something is considered up (e.g. status code, parsing JSON, etc.). I think the current JSON endpoint is great for this purpose, as it allows quick set-up (using `globalStatus`) and more fine-grained control (using each check's status).

Ultimately, it's your call. I see value in not having to maintain the routing config and controller, and implementing this in an application is very easy thanks to the serializable results.

**Comment by tarjei** [comment]
I would +1 the JSON endpoint. Also I use the nagios checks all the time. They do not depend on anything other than the JSON endpoing so the code there is mainly just basic pointers for people running various monitoring tools. 

What I would love to see is an option for a check to add a link in it's response so that an operator can follow that link to some kind of interface for handling the error. For example when I got some failing errors in a queue, linking to a list of the events in that wueue that failed is very usefull. Also this can be used to add runbooks and other documentation to a monitor.

**Comment by kbond** [comment]
Thanks for the feedback @tarjei. What you're describing is actually why I'm against adding the end point to the bundle itself: too many custom implementations. This PR improves the DX of the bundle to a point where this is trivial. For instance, I use a health monitoring service in my app and with this PR it's just a few lines of _bridge_ code in a controller. It takes the check results and maps them to the json this service requires.

**Pull request merged**
