### PR TITLE
Doctrine migrations bundle v2.0.0 compatibility

### PR DESCRIPTION
**Pull request by stopfstedt**
refs #202 

see: https://github.com/doctrine/migrations/blob/master/UPGRADE.md#upgrade-to-20

### CODE REVIEW

**Comment by kbond** [comment]
Isn't there a problem with the `DoctrineMigration` check from [zend-diagnostics](https://github.com/zendframework/zend-diagnostics/blob/94e743e760444800ca44522a9673264a1149dfab/src/Check/DoctrineMigration.php)

It still references `Doctrine\DBAL\Migrations\Configuration\Configuration`

Perhaps a BC layer should be added.

**Comment by jrjohnson** [comment]
Updates to the check are in https://github.com/zendframework/zend-diagnostics/pull/97 with a BC layer.

**Comment by jrjohnson** [comment]
`zend-diagnostics` has been updated and [1.5.0](https://github.com/zendframework/zend-diagnostics/releases/tag/v1.5.0) contains the needed updates for this.

**Comment by kbond** [comment]
Ok, great. Does that mean this PR is not required?

**Comment by jrjohnson** [comment]
No, this PR is still required as the namespaces will need to be changed. The upstream updates adds the shim layer and this PR should just be updated to require at least v1.5.0. As far as I can tell that will support both old and new doctrine migration versions.

**Comment by kbond** [comment]
What needs to be done here?

**Comment by lsmith77** [comment]
I guess this needs a rebase now?

that being said .. do we want to drop support for `^1.,1` or do we want to support both?

**Comment by kbond** [comment]
It sounds like `zend-diagnostics` 1.5+ has the shim needed to support both.

**Comment by lsmith77** [comment]
ah sweet

**Comment by jrjohnson** [comment]
@stopfstedt it looks like updating `doctrine/migrations` to `~2.0` is also necessary in order to get composer to resolve. The breaking changes in that version looks like things you've already addressed here anyway.  https://github.com/doctrine/migrations/blob/2.0/UPGRADE.md

**Comment by kbond** [comment]
Changing `sensiolabs/security-checker` to be `^5.0` should fix the test.

**Comment by lsmith77** [comment]
related to the changes made .. so we still support ^1.1 ? in that case the error message should state so and we should probably also run tests against both versions

**Comment by jrjohnson** [comment]
@lsmith77 I'm not sure what needs to be done after your message. Sounds like maybe you're advocating dropping `^1.1` support?, which I'm all for if you are (not that I really have a vote 😄 ) as a way to move forward.

**Comment by lsmith77** [comment]
no I was more leaning towards keeping `^1.1` but updating our tests to make sure we cover that version as well.

but at any rate send out https://twitter.com/lsmith/status/1146310456807690242

**Comment by kbond** [comment]
I'm fine with dropping `1.x` support

**Comment by lsmith77** [comment]
ok .. didn't get any opposition and given the fact that the 2.0 dependencies are not much different than 1.1, lets do it.

**Comment by lsmith77** [comment]
BTW I guess we do not technically prevent 1.1 but we do not officially support it either.

**Comment by lsmith77** [comment]
I guess next release should be 2.8.0 ?

I don't have a project I can test this on atm .. @kbond can you handle final testing and making the release?

**Comment by kbond** [comment]
Good news is the check still seems to work with doctrine/migrations 1.1 but I had an error when testing with 2.0 (see #211)

**Pull request merged**
